[2024-11-12T19:07:51.301+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T19:07:51.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [queued]>
[2024-11-12T19:07:51.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [queued]>
[2024-11-12T19:07:51.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T19:07:51.534+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-11 11:30:00+00:00
[2024-11-12T19:07:51.574+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_analysis_dag', 'dbt_run', 'scheduled__2024-11-11T11:30:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/DAG for dbt.py', '--cfg-path', '/tmp/tmpyxpug2kj']
[2024-11-12T19:07:51.584+0000] {standard_task_runner.py:91} INFO - Job 175: Subtask dbt_run
[2024-11-12T19:07:51.619+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=220) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T19:07:51.626+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2024-11-12T19:07:51.812+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_stock_analysis_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [running]> on host f3d2ff879b5a
[2024-11-12T19:07:52.257+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Utkarsh Tripathi' AIRFLOW_CTX_DAG_ID='dbt_stock_analysis_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T11:30:00+00:00'
[2024-11-12T19:07:52.260+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T19:07:52.317+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T19:07:52.325+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T19:07:52.346+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T19:07:52.347+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/***/.local/bin/dbt: No such file or directory
[2024-11-12T19:07:52.349+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T19:07:52.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T19:07:52.378+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T19:07:52.393+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_stock_analysis_dag, task_id=dbt_run, run_id=scheduled__2024-11-11T11:30:00+00:00, execution_date=20241111T113000, start_date=20241112T190751, end_date=20241112T190752
[2024-11-12T19:07:52.445+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 175 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 230)
[2024-11-12T19:07:52.476+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T19:07:52.537+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T19:07:52.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
