[2024-11-12T04:37:59.530+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T04:37:59.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:37:58.694804+00:00 [queued]>
[2024-11-12T04:37:59.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:37:58.694804+00:00 [queued]>
[2024-11-12T04:37:59.610+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T04:37:59.641+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 04:37:58.694804+00:00
[2024-11-12T04:37:59.652+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T04:37:58.694804+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp20qjrbij']
[2024-11-12T04:37:59.655+0000] {standard_task_runner.py:91} INFO - Job 159: Subtask dbt_run
[2024-11-12T04:37:59.656+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=309) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T04:37:59.657+0000] {standard_task_runner.py:63} INFO - Started process 310 to run task
[2024-11-12T04:37:59.723+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T04:37:58.694804+00:00 [running]> on host f3d2ff879b5a
[2024-11-12T04:37:59.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T04:37:58.694804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T04:37:58.694804+00:00'
[2024-11-12T04:37:59.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T04:37:59.952+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T04:37:59.954+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T04:37:59.964+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T04:37:59.966+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/***/.local/bin/dbt: No such file or directory
[2024-11-12T04:37:59.967+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T04:37:59.968+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T04:37:59.983+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T04:37:59.991+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T04:37:58.694804+00:00, execution_date=20241112T043758, start_date=20241112T043759, end_date=20241112T043759
[2024-11-12T04:38:00.010+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 159 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 310)
[2024-11-12T04:38:00.035+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T04:38:00.062+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T04:38:00.071+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
