[2024-11-12T20:23:02.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T20:23:02.922+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [queued]>
[2024-11-12T20:23:02.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [queued]>
[2024-11-12T20:23:02.948+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T20:23:02.975+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 20:23:01.701957+00:00
[2024-11-12T20:23:02.985+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_analysis_dag', 'dbt_run', 'manual__2024-11-12T20:23:01.701957+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/DAG for dbt.py', '--cfg-path', '/tmp/tmpj0thniyq']
[2024-11-12T20:23:02.988+0000] {standard_task_runner.py:91} INFO - Job 191: Subtask dbt_run
[2024-11-12T20:23:02.990+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=387) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T20:23:02.991+0000] {standard_task_runner.py:63} INFO - Started process 388 to run task
[2024-11-12T20:23:03.051+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [running]> on host 16d7368eac06
[2024-11-12T20:23:03.208+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Utkarsh Tripathi' AIRFLOW_CTX_DAG_ID='dbt_stock_analysis_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T20:23:01.701957+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T20:23:01.701957+00:00'
[2024-11-12T20:23:03.209+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T20:23:03.230+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T20:23:03.232+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T20:23:03.241+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T20:23:06.164+0000] {subprocess.py:93} INFO - [0m20:23:06  Running with dbt=1.8.7
[2024-11-12T20:23:07.594+0000] {subprocess.py:93} INFO - [0m20:23:07  Registered adapter: snowflake=1.8.4
[2024-11-12T20:23:08.492+0000] {subprocess.py:93} INFO - [0m20:23:08  Encountered an error:
[2024-11-12T20:23:08.493+0000] {subprocess.py:93} INFO - 'dbt_snowflake://macros/metadata.sql'
[2024-11-12T20:23:08.495+0000] {subprocess.py:93} INFO - [0m20:23:08  Traceback (most recent call last):
[2024-11-12T20:23:08.496+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2024-11-12T20:23:08.497+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-11-12T20:23:08.498+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.498+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2024-11-12T20:23:08.499+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:23:08.499+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.500+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2024-11-12T20:23:08.501+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:23:08.501+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.502+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2024-11-12T20:23:08.502+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:23:08.503+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.503+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2024-11-12T20:23:08.503+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:23:08.504+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.504+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2024-11-12T20:23:08.504+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-11-12T20:23:08.505+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.505+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2024-11-12T20:23:08.506+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-11-12T20:23:08.506+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:23:08.507+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2024-11-12T20:23:08.507+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-11-12T20:23:08.508+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^
[2024-11-12T20:23:08.508+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 399, in load
[2024-11-12T20:23:08.509+0000] {subprocess.py:93} INFO -     self.load_and_parse_macros(project_parser_files)
[2024-11-12T20:23:08.509+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 676, in load_and_parse_macros
[2024-11-12T20:23:08.510+0000] {subprocess.py:93} INFO -     block = FileBlock(self.manifest.files[file_id])
[2024-11-12T20:23:08.510+0000] {subprocess.py:93} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2024-11-12T20:23:08.510+0000] {subprocess.py:93} INFO - KeyError: 'dbt_snowflake://macros/metadata.sql'
[2024-11-12T20:23:08.511+0000] {subprocess.py:93} INFO - 
[2024-11-12T20:23:11.451+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T20:23:11.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T20:23:11.465+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T20:23:11.475+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_stock_analysis_dag, task_id=dbt_run, run_id=manual__2024-11-12T20:23:01.701957+00:00, execution_date=20241112T202301, start_date=20241112T202302, end_date=20241112T202311
[2024-11-12T20:23:11.496+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 191 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 388)
[2024-11-12T20:23:11.542+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T20:23:11.569+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T20:23:11.575+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
