[2024-11-12T20:28:11.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T20:28:11.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [queued]>
[2024-11-12T20:28:11.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [queued]>
[2024-11-12T20:28:11.957+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-12T20:28:11.976+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 20:23:01.701957+00:00
[2024-11-12T20:28:11.984+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_analysis_dag', 'dbt_run', 'manual__2024-11-12T20:23:01.701957+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/DAG for dbt.py', '--cfg-path', '/tmp/tmpm65xzrib']
[2024-11-12T20:28:11.987+0000] {standard_task_runner.py:91} INFO - Job 192: Subtask dbt_run
[2024-11-12T20:28:11.988+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=761) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T20:28:11.988+0000] {standard_task_runner.py:63} INFO - Started process 762 to run task
[2024-11-12T20:28:12.037+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_stock_analysis_dag.dbt_run manual__2024-11-12T20:23:01.701957+00:00 [running]> on host 16d7368eac06
[2024-11-12T20:28:12.176+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Utkarsh Tripathi' AIRFLOW_CTX_DAG_ID='dbt_stock_analysis_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T20:23:01.701957+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T20:23:01.701957+00:00'
[2024-11-12T20:28:12.178+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T20:28:12.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T20:28:12.195+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T20:28:12.206+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T20:28:14.518+0000] {subprocess.py:93} INFO - [0m20:28:14  Running with dbt=1.8.7
[2024-11-12T20:28:15.670+0000] {subprocess.py:93} INFO - [0m20:28:15  Registered adapter: snowflake=1.8.4
[2024-11-12T20:28:16.713+0000] {subprocess.py:93} INFO - [0m20:28:16  Encountered an error:
[2024-11-12T20:28:16.714+0000] {subprocess.py:93} INFO - 'dbt_snowflake://macros/catalog.sql'
[2024-11-12T20:28:16.715+0000] {subprocess.py:93} INFO - [0m20:28:16  Traceback (most recent call last):
[2024-11-12T20:28:16.716+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2024-11-12T20:28:16.717+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-11-12T20:28:16.718+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.718+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2024-11-12T20:28:16.719+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:28:16.720+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.721+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2024-11-12T20:28:16.721+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:28:16.722+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.723+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2024-11-12T20:28:16.723+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:28:16.724+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.725+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2024-11-12T20:28:16.726+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-12T20:28:16.726+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.727+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2024-11-12T20:28:16.728+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-11-12T20:28:16.729+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.730+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2024-11-12T20:28:16.731+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-11-12T20:28:16.732+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-12T20:28:16.732+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2024-11-12T20:28:16.733+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-11-12T20:28:16.734+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^
[2024-11-12T20:28:16.734+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 399, in load
[2024-11-12T20:28:16.735+0000] {subprocess.py:93} INFO -     self.load_and_parse_macros(project_parser_files)
[2024-11-12T20:28:16.735+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 676, in load_and_parse_macros
[2024-11-12T20:28:16.736+0000] {subprocess.py:93} INFO -     block = FileBlock(self.manifest.files[file_id])
[2024-11-12T20:28:16.736+0000] {subprocess.py:93} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2024-11-12T20:28:16.737+0000] {subprocess.py:93} INFO - KeyError: 'dbt_snowflake://macros/catalog.sql'
[2024-11-12T20:28:16.737+0000] {subprocess.py:93} INFO - 
[2024-11-12T20:28:18.716+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T20:28:18.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T20:28:18.742+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T20:28:18.749+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_stock_analysis_dag, task_id=dbt_run, run_id=manual__2024-11-12T20:23:01.701957+00:00, execution_date=20241112T202301, start_date=20241112T202811, end_date=20241112T202818
[2024-11-12T20:28:18.775+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 192 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 762)
[2024-11-12T20:28:18.809+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T20:28:18.835+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T20:28:18.844+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
