[2024-11-12T19:50:27.960+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T19:50:28.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T19:50:27.003418+00:00 [queued]>
[2024-11-12T19:50:28.027+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T19:50:27.003418+00:00 [queued]>
[2024-11-12T19:50:28.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T19:50:28.048+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-12 19:50:27.003418+00:00
[2024-11-12T19:50:28.059+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-12T19:50:27.003418+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp8ehrepbz']
[2024-11-12T19:50:28.072+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask dbt_run
[2024-11-12T19:50:28.073+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T19:50:28.074+0000] {standard_task_runner.py:63} INFO - Started process 362 to run task
[2024-11-12T19:50:28.201+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-12T19:50:27.003418+00:00 [running]> on host 16d7368eac06
[2024-11-12T19:50:28.410+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T19:50:27.003418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T19:50:27.003418+00:00'
[2024-11-12T19:50:28.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T19:50:28.441+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T19:50:28.442+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T19:50:28.453+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T19:50:28.454+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /home/***/.local/bin/dbt: No such file or directory
[2024-11-12T19:50:28.455+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T19:50:28.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T19:50:28.468+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T19:50:28.475+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-12T19:50:27.003418+00:00, execution_date=20241112T195027, start_date=20241112T195028, end_date=20241112T195028
[2024-11-12T19:50:28.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 183 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 362)
[2024-11-12T19:50:28.532+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T19:50:28.555+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T19:50:28.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
