[2024-11-12T20:48:04.650+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T20:48:04.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_commands_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [queued]>
[2024-11-12T20:48:04.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_commands_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [queued]>
[2024-11-12T20:48:04.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T20:48:04.734+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-11 11:30:00+00:00
[2024-11-12T20:48:04.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_commands_dag', 'dbt_run', 'scheduled__2024-11-11T11:30:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/DBT_DAG_RUN.py', '--cfg-path', '/tmp/tmp2iexhgae']
[2024-11-12T20:48:04.750+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask dbt_run
[2024-11-12T20:48:04.752+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T20:48:04.755+0000] {standard_task_runner.py:63} INFO - Started process 271 to run task
[2024-11-12T20:48:04.822+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_commands_dag.dbt_run scheduled__2024-11-11T11:30:00+00:00 [running]> on host 16d7368eac06
[2024-11-12T20:48:05.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Utkarsh Tripathi' AIRFLOW_CTX_DAG_ID='dbt_commands_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T11:30:00+00:00'
[2024-11-12T20:48:05.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T20:48:05.031+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T20:48:05.033+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-12T20:48:05.043+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T20:48:09.078+0000] {subprocess.py:93} INFO - [0m20:48:09  Running with dbt=1.8.7
[2024-11-12T20:48:09.102+0000] {subprocess.py:93} INFO - [0m20:48:09  Encountered an error:
[2024-11-12T20:48:09.104+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-12T20:48:09.106+0000] {subprocess.py:93} INFO -   Could not find profile named 'build_utl'
[2024-11-12T20:48:11.659+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-12T20:48:11.660+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T20:48:11.673+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-12T20:48:11.678+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_commands_dag, task_id=dbt_run, run_id=scheduled__2024-11-11T11:30:00+00:00, execution_date=20241111T113000, start_date=20241112T204804, end_date=20241112T204811
[2024-11-12T20:48:11.700+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 271)
[2024-11-12T20:48:11.744+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T20:48:11.776+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T20:48:11.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
